- name: Join new worker nodes to Kubernetes cluster until install containerd
  hosts: new_workers
  become: true

  tasks:
    - name: Install kernel headers
      shell: dnf install -y kernel-devel-$(uname -r)

    - name: Install kernel-modules-extra
      yum:
        name: kernel-modules-extra
        state: present

    - name: Load kernel modules
      shell: |
        modprobe br_netfilter
        modprobe ip_vs
        modprobe ip_vs_rr
        modprobe ip_vs_wrr
        modprobe ip_vs_sh
        modprobe overlay
        modprobe sch_netem

    - name: Configure kernel modules to load on boot
      copy:
        dest: /etc/modules-load.d/kubernetes.conf
        content: |
          br_netfilter
          ip_vs
          ip_vs_rr
          ip_vs_wrr
          ip_vs_sh
          overlay
          sch_netem

    - name: Set sysctl parameters
      copy:
        dest: /etc/sysctl.d/kubernetes.conf
        content: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1

    - name: Apply sysctl parameters
      shell: sysctl --system

    - name: Disable swap
      shell: |
        swapoff -a
        sed -e '/swap/s/^/#/g' -i /etc/fstab

    - name: Add Docker CE repo and install containerd
      shell: |
        dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        dnf makecache
        dnf -y install containerd.io

    - name: Generate default containerd config
      shell: containerd config default > /etc/containerd/config.toml

    - name: Enable SystemdCgroup in containerd config
      replace:
        path: /etc/containerd/config.toml
        regexp: '^\s*SystemdCgroup\s*=\s*false'
        replace: 'SystemdCgroup = true'

    - name: Enable and start containerd
      systemd:
        name: containerd
        enabled: yes
        state: started

    - name: Reboot the machine
      reboot:
        msg: "Rebooting after containerd config change"

