apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appgroups.scheduling.mygroup.io
spec:
  group: scheduling.mygroup.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                workloads:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      selector:
                        type: string
                      weight:
                        type: number
                        format: float
                        description: Overall importance or traffic load weight of the service.
                      dependencies:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            metrics:
                              type: object
                              properties:
                                latency:
                                  type: number
                                bandwidth:
                                  type: number
                                lossrate:
                                  type: number
  scope: Cluster
  names:
    plural: appgroups
    singular: appgroup
    kind: AppGroup
    shortNames:
      - ag