apiVersion: v1
kind: ServiceAccount
metadata:
  name: appgroup-controller-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appgroup-controller-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["scheduling.mygroup.io"]
    resources: ["appgroups"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appgroup-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appgroup-controller-role
subjects:
  - kind: ServiceAccount
    name: appgroup-controller-sa
    namespace: kube-system
