apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf3-server
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: iperf3-server
  template:
    metadata:
      labels:
        app: iperf3-server
    spec:
      containers:
        - name: iperf3
          image: networkstatic/iperf3
          command: ["iperf3", "-s"]
          ports:
            - containerPort: 5201
              hostPort: 5201   # 允许 hostNetwork 访问
              protocol: TCP
      hostNetwork: true         # 让探测端能访问 node IP + 5201
      restartPolicy: Always