# --- 1. Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-aggregator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-aggregator
  template:
    metadata:
      labels:
        app: net-aggregator
    spec:
      containers:
        - name: aggregator
          image: yongyuliu03/net-aggregator:v11
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: sp25-cs525-1402.cs.illinois.edu

---

# --- 2. Service ---
apiVersion: v1
kind: Service
metadata:
  name: net-aggregator
  namespace: kube-system
spec:
  selector:
    app: net-aggregator
  ports:
    - port: 8080
      targetPort: 8080