apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networktopologies.scheduling.mygroup.io
spec:
  group: scheduling.mygroup.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                latency:
                  type: object
                  additionalProperties:
                    type: object
                    additionalProperties:
                      type: number
                bandwidth:
                  type: object
                  additionalProperties:
                    type: object
                    additionalProperties:
                      type: number
                lossrate:
                  type: object
                  additionalProperties:
                    type: object
                    additionalProperties:
                      type: number
                maxLatency:
                  type: number
                maxBandwidth:
                  type: number
                maxLossrate:
                  type: number
                minLatency:
                  type: number
                minBandwidth:
                  type: number
                minLossrate:
                  type: number
  scope: Cluster
  names:
    plural: networktopologies
    singular: networktopology
    kind: NetworkTopology
    shortNames:
      - nt