apiVersion: apps/v1
kind: Deployment
metadata:
  name: appgroup-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appgroup-controller
  template:
    metadata:
      labels:
        app: appgroup-controller
    spec:
      containers:
        - name: controller
          image: yongyuliu03/appgroup-controller:v1
          imagePullPolicy: Always
      serviceAccountName: appgroup-controller-sa
——————

apiVersion: v1
kind: Service
metadata:
  name: appgroup-controller
  namespace: kube-system
spec:
  selector:
    app: appgroup-controller
  ports:
    - port: 8090       
      targetPort: 8090 